### ISSUE TITLE
DLL files are not located in the correct directory

### ISSUE THREAD

**Issue by markasselin** [KitwareMedical/SlicerVirtualReality#13] opened 2017-12-08 19:08 UTC
SlicerOpenVR depends on vtkRenderingOpenVR-8.1.dll and openvr_api.dll, but these are not copied to .\<BUILD-DIR>\inner-build\lib\Slicer-4.9\qt-loadable-modules\Release\ by default.

**Temporary workaround:** Manually copy the following files into \<BUILD-DIR\>\inner-build\lib\Slicer-4.9\qt-loadable-modules\Release\ 
- \<BUILD-DIR\>\bin\Release\vtkRenderingOpenVR-8.1.dll
- \<BUILD-DIR\>\OpenVR\bin\win64\openvr_api.dll (on Windows, macOS will be different)

**Comment by jcfr** [comment] 2017-12-08 20:39
Do you still have a problem after specifying the additional launcher settings:

Copied from the README:

```
./Slicer.exe  --launcher-additional-settings C:\path\to\SlicerOpenVR-build\inner-build\AdditionalLauncherSettings.ini --additional-module-paths C:\path\to\SlicerOpenVR-build\inner-build\
```

**Comment by lassoan** [comment] 2018-02-15 05:04
This issue is duplicate of #2

**Comment by jcfr** [comment] 2018-02-15 05:06
Closing. Fixed in https://github.com/KitwareMedical/SlicerVirtualReality/pull/23

**Closed by jcfr** 2018-02-15 05:06 UTC
