### ISSUE TITLE
Volume rendering is too bright

### ISSUE THREAD

**Issue by markasselin** [KitwareMedical/SlicerVirtualReality#10] opened 2017-12-08 18:54 UTC
In Slicer
![volumerendering-slicer](https://user-images.githubusercontent.com/17535566/33780598-53c1b334-dc1f-11e7-996f-0d3df60023d1.PNG)

In OpenVR on the HTC VIVE
![volumerendering-vr](https://user-images.githubusercontent.com/17535566/33780599-53cff5d4-dc1f-11e7-9903-67070a99315a.PNG)

**Comment by jcfr** [comment] 2017-12-08 20:37
After talking with @martinken, this is explained by the  four lights [specific to the VR view](https://github.com/KitwareMedical/SlicerOpenVR/blob/df15bf8e2cb630b2c137a9830b0b2747c6144409/VR/Widgets/qMRMLVRView.cxx#L166-L194). 

As soon as VTK volume rendering is improved to deal with this, we will make sure to update the Slicer extension.

**Comment by mattjolley** [comment] 2018-01-03 23:37
We have noticed this as well.  Thank you for taking a look at it.

**Comment by jcfr** [comment] 2018-01-11 12:46
After further discussion with @sankhesh  and @martinken, the issue is most likely related to two sided lighting and is not specific to OpenVR.

To address this, a new option was added to VTK OpenGl2 mapper:
* https://gitlab.kitware.com/vtk/vtk/blob/5022590e19effc52c4ef6b5152c1e3c0691d64cb/Rendering/VolumeOpenGL2/vtkVolumeShaderComposer.h#L607-614
* https://github.com/Kitware/VTK/blame/master/Rendering/Core/vtkRenderer.h#L123-L132

**Comment by jcfr** [comment] 2018-01-11 12:49
After:
* address VTK issue preventing it from building. [VTK fails to build with -DModule_vtkRenderingFreeTypeFontConfig:BOOL=ON and Python wrapping](https://gitlab.kitware.com/vtk/vtk/issues/17217)
* updating the version of VTKv9 in Slicer
* enabling VTKv9+Qt5 in the Windows build
* Updating Slicer to include [this patch](https://github.com/Slicer/Slicer/commit/4fab097ec7ed88958046cb568453a69071b86034)

The SlicerOpenVR extension should be available for download in the appstore for windows build

**Comment by mattjolley** [comment] 2018-01-11 13:47
@jcfr 
<After further discussion with @sankhesh and @martinken, the issue is most likely related to two sided lighting and is not specific to OpenVR.>

@markasselin deleted two of the lights (of four?) and the VIVE image mirrored that of the computer screen, suggesting your hypothesis above was correct.

**Comment by mattjolley** [comment] 2018-01-11 23:30
@jcfr 
@markasselin  
Should we set the default for VR to 2 lights somehow or add option for that to the GUI?  Maybe this has already been done.  Thank you.

**Comment by cpinter** [comment] 2018-01-17 00:13
@markasselin As far as I remember you fixed this. If so can you close it? Thanks

**Comment by jcfr** [comment] 2018-01-17 00:52
> fixed this. If so can you close it? Thanks

We need the four lights for everything expect Volume Rendering.

Now that Slicer is building against on updated VTKv9, it is now possible to set `TwoSidedLighting` renderer property that should help.

**Comment by mattjolley** [comment] 2018-02-11 17:46
We have been working with volume rendered echo in VR and can confirm the issue still exists for volume rendered objects (with 4 lights), but that the VR images look great for non-volume rendered surfaces such as segmentations (with the 4 lights).  

Having the option in the volume rendering module GUI might be a good way to address this.  

One thing it does not address is sometimes we mix volume rendered images and segmented images,  is there any way to address what you do in that case (for optimal viewing of both?).  Clearly this is lower priority, but something to think about.

**Comment by lassoan** [comment] 2018-02-15 05:56
@jcfr Do I understand correctly that the solution is to have a scene with better lighting is:
1. remove the [extra lights](https://github.com/KitwareMedical/SlicerVirtualReality/blob/df15bf8e2cb630b2c137a9830b0b2747c6144409/VR/Widgets/qMRMLVRView.cxx#L166-L194)
2. enable TwoSidedLighting option somewhere [here](https://github.com/KitwareMedical/SlicerVirtualReality/blob/df15bf8e2cb630b2c137a9830b0b2747c6144409/VR/Widgets/qMRMLVRView.cxx#L203)?

**Closed** 2018-02-20 06:15 UTC
