### ISSUE TITLE
Volume Rendering Displaying as a Plane

### ISSUE THREAD

**Issue by sulentica** [KitwareMedical/SlicerVirtualReality#125] opened 2023-10-04 19:09 UTC
I am using the Vive Pro 2 Headset with Slicer 5.4, Virtual Reality Extension from 8/26/23, and Slicer Heart Extension from 9/20/23.

When I try to use the Virtual Reality module to interact with a volume rendered CT, the volume rendering is displaying in the VR scene as a 2D plane. I have tried looking at previously volume rendered files as well as volume rendering from a dicom file and have the same problem. 

Here is a video showing this issue:

https://github.com/KitwareMedical/SlicerVirtualReality/assets/109092840/c91df28f-8367-4b87-8f51-8a8cd53577b6

**Comment by jcfr** [comment] 2023-10-04 19:19
Thanks for the report :pray: 

We will try to reproduce and follow up with question if any. You should expect to hear back within 2 weeks.

**Comment by sulentica** [comment] 2023-10-04 19:21
Thank you!!

**Comment by sulentica** [comment] 2023-11-27 15:52
@jcfr Just wanted to reach back out and see if you were able to reproduce this issue. Let me know if there are any updates I can test, thank you!

@lassoan

**Comment by lassoan** [comment] 2023-11-27 16:21
I've come across an issue about a month ago in the Slicer Preview Release at the time, which may be the same as what you report. The issue was that corner of the volume that got too close to me became transparent, which kind of gave the impression that it is just a 2D plane that I can see behind. When I got closer, the whole volume disappeared. 3D compositing seemed to work well in areas where the volume rendering was visible, but the disappearing corners kind of broke the 3D cues. I could work around the issue by playing with the scale of the scene: if I made the 3D volume very large then I could walk in and soo inside but at normal scale when I got close to the volume it started to disappear.

@jcfr it would be great if somebody could test volume rendering close to (or inside) the volume using the latest Slicer version.

**Comment by mattjolley** [comment] 2023-11-27 16:34
@sulentica @lassoan 

Does it happen with segmented models or just volume rendering?

**Comment by lassoan** [comment] 2023-11-27 17:13
For me it happened with just volume rendering.

**Comment by mattjolley** [comment] 2023-11-27 17:18
Thank you @lassoan 

@sulentica 

We should try with the shells (Segmented models) to isolate the issue.

That is all we need for the SV defects.

**Comment by sulentica** [comment] 2023-11-27 21:25
@lassoan @mattjolley 

I used Slicer 5.4 with updated Slicer Heart module. The segmented models worked very well in the virtual reality module!

**Comment by mattjolley** [comment] 2023-11-27 21:25
Thank you for testing @sulentica and team!

**Comment by jcfr** [comment] 2023-12-23 09:49
Closing. Thanks to @sankhesh and @LucasGandel, a fix has been implemented and is being reviewed in upstream VTK through [MR-10783](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10783).

In the meantime, the corresponding fixes have been backported into `Slicer/VTK` so that it is available for both `SlicerStable`[^1] and `SlicerPreview`[^2]

### Details

To ensure proper rendering, particularly by `vtkOpenGLGPUVolumeRaycastMapper`, when the head-mounted display (HMD) is positioned inside the volume. The issue is resolved by ensuring correct computation of the plane frustum when the camera is tracking the HMD and is positioned inside the volume.

The computation of the plane frustum is adapted to account for the left or right eye matrices explicitly created for VR. Note that the updated logic adjusts the frustum computation: it utilizes the left/right matrices when tracking the HMD, and defaults to the regular frustum computation method based on the viewport aspect ratio if hardware picking is enabled. In hardware picking scenarios, the camera's viewpoint is aligned with the wand controller, and TrackHMD is disabled to maintain stability and prevent unintended scene changes.


[^1]: https://github.com/Slicer/VTK/pull/48
[^2]: https://github.com/Slicer/VTK/pull/49

**Closed by jcfr** 2023-12-23 09:49 UTC
Labels: bug, Domain: OpenVR
