### ISSUE TITLE
3D pinch function is unreliable

### ISSUE THREAD

**Issue by cpinter** [KitwareMedical/SlicerVirtualReality#124] opened 2023-09-14 09:54 UTC
The two-handed gesture that allows to rotate/scale the world only works around half the time. See video here
https://discourse.slicer.org/t/5-4-vr-testride/31252/3?u=cpinter

Is it possible that the `RecognizeComplexGesture` function has changed again? Or some other change in VTK causes this?

It used to work perfectly with [Slicer 98c092edb8f5a274277d2e486a4f7e584f58605e](https://github.com/Slicer/Slicer/commit/98c092edb8f5a274277d2e486a4f7e584f58605e)  (5.3.0 nightly 2023.06.19.)

**Comment by LucasGandel** [comment] 2023-09-22 06:55
I wonder if this regression is caused by [VTK@c07e0186](https://gitlab.kitware.com/vtk/vtk/-/commit/c07e018641af68895c5123b32310bb44325deefc) and [VTK@7ecbf4f](https://gitlab.kitware.com/vtk/vtk/-/commit/7ecbf4f12feb6dd06f64e69324f753f7876ce24e). Both were merged in VTK before 2023.06.19, but I don't know when Slicer started to use them.

**Closed** 2023-12-21 23:13 UTC
Labels: bug, Domain: OpenVR
